### ISSUE TITLE
Does this module work with Android?

### ISSUE THREAD

**Issue by Shin-NiL** [khairul169/gdsqlite#7]
Hello there, first of all thanks for sharing your great module :)

My question is: do you know if this module works with Android and Godot 2.1 stable? I've tested with Windows templates and is working just fine, but when I tried on Android, I got this errors:

```
I/godot   ( 6453): OpenSL Init OK!
I/godot   ( 6453): [1;35mSCRIPT ERROR: GDScript::load_byte_code: [0m[1mCompile Error: Identifier not found: SQLite
I/godot   ( 6453): [0;35m   At: res://main.gdc:3.[0m
I/godot   ( 6453): [1;31mERROR: load_byte_code: [0m[1mMethod/Function Failed, returning: ERR_COMPILATION_FAILED
I/godot   ( 6453): [0;31m   At: modules\gdscript\gd_script.cpp:728.[0m
I/godot   ( 6453): [1;31mERROR: load: [0m[1mCondition ' err!=OK ' is true. returned: RES()
I/godot   ( 6453): [0;31m   At: modules\gdscript\gd_script.cpp:1859.[0m
I/godot   ( 6453): [1;31mERROR: load: [0m[1mMethod/Function Failed, returning: RES()
I/godot   ( 6453): [0;31m   At: core\io\resource_loader.cpp:218.[0m
I/godot   ( 6453): [1;31mERROR: poll: [0m[1mMethod/Function Failed, returning: error
I/godot   ( 6453): [0;31m   At: core\io\resource_format_binary.cpp:681.[0m
I/godot   ( 6453): [1;31mERROR: load: [0m[1mCondition ' err!=OK ' is true. returned: RES()
I/godot   ( 6453): [0;31m   At: core\io\resource_loader.cpp:142.[0m
I/godot   ( 6453): [1;31mERROR: load: [0m[1mMethod/Function Failed, returning: RES()
I/godot   ( 6453): [0;31m   At: core\io\resource_loader.cpp:218.[0m
I/godot   ( 6453): [1;31mERROR: start: [0m[1mCondition ' !scene ' is true. returned: false
I/godot   ( 6453): [0;31m   At: main\main.cpp:1464.[0m
```

Thanks.

**Comment by gerardogc2378** [comment]
I have issues with Android too, please Android support for this great module!

**Comment by RameshRavone** [comment]
There are some parsing error in this module, so a `bug`

**Comment by samuelpedrajas** [comment]
I'm having the same issue. It works fine in the editor but it doesn't work on Android. Did anyone find any solution to this?

**Comment by avril-gh** [comment]
Godot 2.1.5 at https://github.com/godotengine/godot/commit/8d75ea755cb933a5c4a0f9ec296e8b8c34ef9999
gdSQLite for godot 2.x  at 850bf24

compile editor - ok.
compile for android - ok
works on windows 7 32 - ok
works on android 4.4.2 MTK6591 MALI450PM4 - ok

_great and VERY USEFUL module btw_

to the ones who cant make it work
please make sure that both editor and export templates are compiled from the same version with gdSQLite included.

**Comment by gerardogc2378** [comment]
Thanks a lot. So the thing here is compilate all godot itself and produce a new export template with this module. :+1:

**Comment by Shin-NiL** [comment]
Tested with 2.1.6 and is working fine on Android.

**Comment by avril-gh** [comment]
@Shin-NiL 
i have this module updated for godot 3.x if you're interested
https://github.com/avril-gh/gdsqlite/tree/godot-3.x

**Comment by Shin-NiL** [comment]
@avril-gh 
Nice, thanks!

**Comment by gerardogc2378** [comment]
Thanks!!!
