### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by GrandFunkR** [khairul169/gdsqlite#8]
In file included from modules/gdsqlite/gdsqlite.cpp:3:0:
modules/gdsqlite/gdsqlite.h:12:27: error: ISO C++ forbids declaration of 'OBJ_TYPE' with no type [-fpermissive]
  OBJ_TYPE(SQLite,Reference);
                           ^
In file included from modules/gdsqlite/register_types.cpp:6:0:
modules/gdsqlite/gdsqlite.h:12:27: error: ISO C++ forbids declaration of 'OBJ_TYPE' with no type [-fpermissive]
  OBJ_TYPE(SQLite,Reference);
                           ^
modules/gdsqlite/register_types.cpp: In function 'void register_gdsqlite_types()':
modules/gdsqlite/register_types.cpp:10:9: error: 'ObjectTypeDB' has not been declared
         ObjectTypeDB::register_type<SQLite>();
         ^~~~~~~~~~~~
[...]

**Comment by khairul169** [comment]
Does you compile it with latest commit of godot engine?
Juan have changed ObjectTypeDB to ClassDB and OBJ_TYPE to GDCLASS, so it break the compatibility..
You can compile it with godot 2.2 branch :+1:

**Comment by GrandFunkR** [comment]
yes, compiled with  latest commit of godot engine. 
It is there a way to adapt the code and make it work with the latest sources of godot?

**Comment by khairul169** [comment]
I'm not tried it yet, but maybe you can replace ObjectTypeDB to ClassDB and OBJ_TYPE to GDCLASS..

**Comment by GrandFunkR** [comment]
ty, seems to works replacing
ObjectTypeDB to ClassDB
OBJ_TYPE to GDCLASS
register_types to register_class
Globals to GlobalConfig

**Comment by MarianoGnu** [comment]
compiling now, i did the very same changes GrandFunkR did, if we get a DEFINE from godot containing the current major version i belive we can make this module to compile for both versions.

**Comment by khairul169** [comment]
Thanks! i've pushed a commit to master branch for 3.0 support.. There is a 2.x branch if anyone want to use it with godot 2.x :+1:

**Comment by MarianoGnu** [comment]
i supose this issue can be closed then

**Comment by khairul169** [comment]
yeah
